AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

Resources:
   s3bucket-01:
    Type: AWS::S3::Bucket
Properties:
  BucketEncryption: 
    BucketEncryption
  BucketName: s3bucket-01
  